/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "欧呀Ocean Space",
  "description": "Ocean的博客，一个致力于将自己的收获和经验分享给大家的个人网站",
  "base": "/ohblog/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "meta",
      {
        "name": "Keywords",
        "content": "Ocean的博客,Web前端,笔记,日常,项目,vue,javascript,程序员"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/ohblog/assets/img/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Ocean's Blog",
        "tagline": "Tech Otakus Save The World"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-63a96fe4",
      "path": "/",
      "lastUpdated": "2 天",
      "lastUpdatedTimestamp": 1645302674000,
      "createdTime": 1645302674000
    },
    {
      "title": "后台管理系统项目总结",
      "frontmatter": {
        "title": "后台管理系统项目总结",
        "categories": [
          "项目总结"
        ],
        "tags": [
          "vue",
          "element-ui",
          "node"
        ],
        "date": "2022-2-19"
      },
      "regularPath": "/blog/%E5%89%8D%E7%AB%AF%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%E6%80%BB%E7%BB%93%EF%BC%9A%E7%94%B5%E5%95%86%E5%90%8E%E5%8F%B0%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F.html",
      "relativePath": "blog/前端项目开发总结：电商后台管理系统.md",
      "key": "v-34324faf",
      "path": "/blog/%E5%89%8D%E7%AB%AF%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%E6%80%BB%E7%BB%93%EF%BC%9A%E7%94%B5%E5%95%86%E5%90%8E%E5%8F%B0%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "前言：",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "一、项目主要功能模块划分",
          "slug": "一、项目主要功能模块划分"
        },
        {
          "level": 2,
          "title": "二、各功能模块的实现",
          "slug": "二、各功能模块的实现"
        },
        {
          "level": 3,
          "title": "2.1 ==项目初始化==",
          "slug": "_2-1-项目初始化"
        },
        {
          "level": 3,
          "title": "2.2 ==登录/退出功能==",
          "slug": "_2-2-登录-退出功能"
        },
        {
          "level": 3,
          "title": "2.3 主页布局",
          "slug": "_2-3-主页布局"
        },
        {
          "level": 3,
          "title": "2.4 用户管理模块",
          "slug": "_2-4-用户管理模块"
        },
        {
          "level": 3,
          "title": "2.5 ==权限管理==",
          "slug": "_2-5-权限管理"
        },
        {
          "level": 3,
          "title": "2.6 ==分类管理==",
          "slug": "_2-6-分类管理"
        },
        {
          "level": 3,
          "title": "2.7 ==参数管理==",
          "slug": "_2-7-参数管理"
        },
        {
          "level": 3,
          "title": "2.8 ==商品管理==",
          "slug": "_2-8-商品管理"
        },
        {
          "level": 3,
          "title": "2.9 订单管理",
          "slug": "_2-9-订单管理"
        },
        {
          "level": 3,
          "title": "2.10 ==数据统计==",
          "slug": "_2-10-数据统计"
        }
      ],
      "lastUpdated": "2 天",
      "lastUpdatedTimestamp": 1645302674000,
      "createdTime": 1645302674000
    },
    {
      "title": "js中创建二维数组的坑",
      "frontmatter": {
        "title": "js中创建二维数组的坑",
        "categories": [
          "前端"
        ],
        "tags": [
          "javascript"
        ],
        "date": "2022-2-19"
      },
      "regularPath": "/blog/%E5%85%B3%E4%BA%8EJs%E4%B8%AD%E5%88%9B%E5%BB%BA%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84%E7%9A%84%E5%9D%91.html",
      "relativePath": "blog/关于Js中创建二维数组的坑.md",
      "key": "v-503ccbb9",
      "path": "/blog/%E5%85%B3%E4%BA%8EJs%E4%B8%AD%E5%88%9B%E5%BB%BA%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84%E7%9A%84%E5%9D%91.html",
      "headers": [
        {
          "level": 2,
          "title": "==遇到问题的方法:==",
          "slug": "遇到问题的方法"
        }
      ],
      "lastUpdated": "2 天",
      "lastUpdatedTimestamp": 1645302674000,
      "createdTime": 1645302674000
    },
    {
      "title": "JavaScript事件循环机制",
      "frontmatter": {
        "title": "JavaScript事件循环机制",
        "categories": [
          "前端"
        ],
        "tags": [
          "javascript"
        ],
        "date": "2022-2-19",
        "cover": "https://www.zpzpup.com/assets/image/gd04.jpg"
      },
      "regularPath": "/blog/%E5%AF%B9JavaScript%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF%E6%9C%BA%E5%88%B6%E7%9A%84%E7%90%86%E8%A7%A3.html",
      "relativePath": "blog/对JavaScript事件循环机制的理解.md",
      "key": "v-e19f586c",
      "path": "/blog/%E5%AF%B9JavaScript%E4%BA%8B%E4%BB%B6%E5%BE%AA%E7%8E%AF%E6%9C%BA%E5%88%B6%E7%9A%84%E7%90%86%E8%A7%A3.html",
      "headers": [
        {
          "level": 3,
          "title": "一、事件循环和任务队列产生的原因：",
          "slug": "一、事件循环和任务队列产生的原因"
        },
        {
          "level": 3,
          "title": "二、==事件循环机制==：",
          "slug": "二、-事件循环机制"
        },
        {
          "level": 3,
          "title": "三、==任务队列==：",
          "slug": "三、-任务队列"
        },
        {
          "level": 3,
          "title": "四、==强大的异步专家 process.nextTick()==",
          "slug": "四、-强大的异步专家-process-nexttick"
        }
      ],
      "lastUpdated": "2 天",
      "lastUpdatedTimestamp": 1645302674000,
      "createdTime": 1645302674000
    },
    {
      "title": "哈夫曼编译码",
      "frontmatter": {
        "title": "哈夫曼编译码",
        "categories": [
          "数据结构与算法"
        ],
        "tags": [
          "数据结构"
        ],
        "date": "2022-2-19"
      },
      "regularPath": "/blog/%E6%A0%91%E2%80%94%E2%80%94%E5%93%88%E5%A4%AB%E6%9B%BC%E7%BC%96%E8%AF%91%E7%A0%81.html",
      "relativePath": "blog/树——哈夫曼编译码.md",
      "key": "v-3036352a",
      "path": "/blog/%E6%A0%91%E2%80%94%E2%80%94%E5%93%88%E5%A4%AB%E6%9B%BC%E7%BC%96%E8%AF%91%E7%A0%81.html",
      "lastUpdated": "2 天",
      "lastUpdatedTimestamp": 1645302674000,
      "createdTime": 1645302674000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/logo.png",
    "type": "blog",
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "项目",
        "items": [
          {
            "text": "电商后台管理系统",
            "link": ""
          },
          {
            "text": "客运售票网站",
            "link": ""
          }
        ]
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "留言板",
        "link": "",
        "icon": "reco-suggestion"
      },
      {
        "text": "关于我",
        "link": "/about",
        "items": [
          {
            "text": "我的经历",
            "link": ""
          },
          {
            "text": "个人简历",
            "link": ""
          }
        ]
      },
      {
        "text": "其他",
        "link": "",
        "icon": "reco-other"
      }
    ],
    "author": "OceanH",
    "authorAvatar": "/assets/img/avatar.png",
    "friendLink": [
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "logo": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      },
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "recoluan@qq.com",
        "link": "https://www.recoluan.com"
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      },
      "socialLinks": [
        {
          "icon": "reco-github",
          "link": "https://github.com/recoluan"
        },
        {
          "icon": "reco-npm",
          "link": "https://www.npmjs.com/~reco_luan"
        }
      ]
    }
  }
}