/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "javascript": {
      "key": "javascript",
      "scope": "tags",
      "path": "/tag/javascript/",
      "pageKeys": [
        "v-503ccbb9",
        "v-e19f586c"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-34324faf"
      ]
    },
    "element-ui": {
      "key": "element-ui",
      "scope": "tags",
      "path": "/tag/element-ui/",
      "pageKeys": [
        "v-34324faf"
      ]
    },
    "node": {
      "key": "node",
      "scope": "tags",
      "path": "/tag/node/",
      "pageKeys": [
        "v-34324faf"
      ]
    },
    "数据结构": {
      "key": "数据结构",
      "scope": "tags",
      "path": "/tag/数据结构/",
      "pageKeys": [
        "v-3036352a"
      ]
    }
  },
  "categories": {
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-503ccbb9",
        "v-e19f586c"
      ]
    },
    "项目总结": {
      "key": "项目总结",
      "scope": "categories",
      "path": "/categories/项目总结/",
      "pageKeys": [
        "v-34324faf"
      ]
    },
    "数据结构与算法": {
      "key": "数据结构与算法",
      "scope": "categories",
      "path": "/categories/数据结构与算法/",
      "pageKeys": [
        "v-3036352a"
      ]
    }
  },
  "timeline": {}
}