/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "javascript",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/javascript/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/vue/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "element-ui",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/element-ui/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "node",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/node/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "数据结构",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/数据结构/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "前端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "项目总结",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/项目总结/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "数据结构与算法",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/数据结构与算法/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]